name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install gcc dependencies
      run: sudo apt-get update && sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev

    - name: Make toolchain
      run: make -j2
      working-directory: toolchain

    - name: install os dependencies
      run: sudo apt-get install -y mtools

    - name: make ISO
      run: ./iso.sh
      
    - uses: actions/upload-artifact@v3
      with:
        name: myos
        path: |
          myos.iso
          kernel/myos.kernel
